# Generated by Django 4.0 on 2024-03-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medkit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MedicineName', models.CharField(max_length=500)),
                ('Quantity', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=500)),
                ('ExpirationDate', models.CharField(max_length=500)),
            ],
        ),
    ]
