# Generated by Django 4.0 on 2024-03-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablemedicine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='searchb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medname', models.CharField(max_length=500)),
            ],
        ),
    ]
